<?php include 'inc/config.php'; // Configuration php file ?>
<?php include 'inc/top.php'; // Meta data and header ?>
<?php include 'inc/nav.php'; // Navigation content ?>

<!-- Page Content -->
<div id="page-content">
    <!-- Navigation info -->
    <ul id="nav-info" class="clearfix">
        <li><a href="index.php"><i class="fa fa-home"></i></a></li>
        <li><a href="javascript:void(0)">Icons</a></li>
        <li class="active"><a href="">FontAwesome</a></li>
    </ul>
    <!-- END Navigation info -->

    <!-- Font Awesome Icons -->
    <h3 class="page-header page-header-top"><a href="http://fortawesome.github.com/Font-Awesome/" target="_blank">FontAwesome Icons 4.2.0</a> <small>Font based</small></h3>

    <ul class="fa-ul">
        <li><i class="fa fa-li fa-check text-success"></i><strong>479 unique icons designed for use with Bootstrap!</strong></li>
        <li><i class="fa fa-li fa-check text-success"></i><strong>Use it with any color or size you like!</strong></li>
    </ul>

    <!-- Web Application Icons -->
    <h4 class="sub-header">Web Application Icons</h4>
    <ul class="iconset-list clearfix">
        <li><i class="fa fa-adjust"></i> <code>fa fa-adjust</code></li>
        <li><i class="fa fa-anchor"></i> <code>fa fa-anchor</code></li>
        <li><i class="fa fa-archive"></i> <code>fa fa-archive</code></li>
        <li><i class="fa fa-asterisk"></i> <code>fa fa-asterisk</code></li>
        <li><i class="fa fa-automobile"></i> <code>fa fa-automobile</code></li>
        <li><i class="fa fa-ban"></i> <code>fa fa-ban</code></li>
        <li><i class="fa fa-bank"></i> <code>fa fa-bank</code></li>
        <li><i class="fa fa-bar-chart-o"></i> <code>fa fa-bar-chart-o</code></li>
        <li><i class="fa fa-barcode"></i> <code>fa fa-barcode</code></li>
        <li><i class="fa fa-flask"></i> <code>fa fa-flask</code></li>
        <li><i class="fa fa-beer"></i> <code>fa fa-beer</code></li>
        <li><i class="fa fa-bell-o"></i> <code>fa fa-bell-o</code></li>
        <li><i class="fa fa-bell"></i> <code>fa fa-bell</code></li>
        <li><i class="fa fa-bolt"></i> <code>fa fa-bolt</code></li>
        <li><i class="fa fa-book"></i> <code>fa fa-book</code></li>
        <li><i class="fa fa-bomb"></i> <code>fa fa-bomb</code></li>
        <li><i class="fa fa-building"></i> <code>fa fa-building</code></li>
        <li><i class="fa fa-bookmark"></i> <code>fa fa-bookmark</code></li>
        <li><i class="fa fa-bookmark-o"></i> <code>fa fa-bookmark-o</code></li>
        <li><i class="fa fa-briefcase"></i> <code>fa fa-briefcase</code></li>
        <li><i class="fa fa-bug"></i> <code>fa fa-bug</code></li>
        <li><i class="fa fa-building-o"></i> <code>fa fa-building-o</code></li>
        <li><i class="fa fa-bullhorn"></i> <code>fa fa-bullhorn</code></li>
        <li><i class="fa fa-bullseye"></i> <code>fa fa-bullseye</code></li>
        <li><i class="fa fa-calendar"></i> <code>fa fa-calendar</code></li>
        <li><i class="fa fa-calendar-o"></i> <code>fa fa-calendar-o</code></li>
        <li><i class="fa fa-cab"></i> <code>fa fa-cab</code></li>
        <li><i class="fa fa-car"></i> <code>fa fa-car</code></li>
        <li><i class="fa fa-camera"></i> <code>fa fa-camera</code></li>
        <li><i class="fa fa-camera-retro"></i> <code>fa fa-camera-retro</code></li>
        <li><i class="fa fa-certificate"></i> <code>fa fa-certificate</code></li>
        <li><i class="fa fa-check-square-o"></i> <code>fa fa-check-square-o</code></li>
        <li><i class="fa fa-square-o"></i> <code>fa fa-square-o</code></li>
        <li><i class="fa fa-minus-square-o"></i> <code>fa fa-minus-square-o</code></li>
        <li><i class="fa fa-check-square"></i> <code>fa fa-check-square</code></li>
        <li><i class="fa fa-child"></i> <code>fa fa-child</code></li>
        <li><i class="fa fa-circle"></i> <code>fa fa-circle</code></li>
        <li><i class="fa fa-circle-o"></i> <code>fa fa-circle-o</code></li>
        <li><i class="fa fa-circle-o-notch"></i> <code>fa fa-circle-o-notch</code></li>
        <li><i class="fa fa-circle-thin"></i> <code>fa fa-circle-thin</code></li>
        <li><i class="fa fa-cloud"></i> <code>fa fa-cloud</code></li>
        <li><i class="fa fa-cloud-download"></i> <code>fa fa-cloud-download</code></li>
        <li><i class="fa fa-cloud-upload"></i> <code>fa fa-cloud-upload</code></li>
        <li><i class="fa fa-code"></i> <code>fa fa-code</code></li>
        <li><i class="fa fa-code-fork"></i> <code>fa fa-code-fork</code></li>
        <li><i class="fa fa-coffee"></i> <code>fa fa-coffee</code></li>
        <li><i class="fa fa-cog"></i> <code>fa fa-cog</code></li>
        <li><i class="fa fa-cogs"></i> <code>fa fa-cogs</code></li>
        <li><i class="fa fa-caret-square-o-down"></i> <code>fa fa-caret-square-o-down</code></li>
        <li><i class="fa fa-minus-square-o"></i> <code>fa fa-minus-square-o</code></li>
        <li><i class="fa fa-caret-square-o-up"></i> <code>fa fa-caret-square-o-up</code></li>
        <li><i class="fa fa-comment"></i> <code>fa fa-comment</code></li>
        <li><i class="fa fa-comment-o"></i> <code>fa fa-comment-o</code></li>
        <li><i class="fa fa-comments"></i> <code>fa fa-comments</code></li>
        <li><i class="fa fa-comments-o"></i> <code>fa fa-comments-o</code></li>
        <li><i class="fa fa-compass"></i> <code>fa fa-compass</code></li>
        <li><i class="fa fa-credit-card"></i> <code>fa fa-credit-card</code></li>
        <li><i class="fa fa-crop"></i> <code>fa fa-crop</code></li>
        <li><i class="fa fa-tachometer"></i> <code>fa fa-tachometer</code></li>
        <li><i class="fa fa-database"></i> <code>fa fa-database</code></li>
        <li><i class="fa fa-desktop"></i> <code>fa fa-desktop</code></li>
        <li><i class="fa fa-dot-circle-o"></i> <code>fa fa-dot-circle-o</code></li>
        <li><i class="fa fa-arrow-circle-o-down"></i> <code>fa fa-arrow-circle-o-down</code></li>
        <li><i class="fa fa-download"></i> <code>fa fa-download</code></li>
        <li><i class="fa fa-pencil-square-o"></i> <code>fa fa-pencil-square-o</code></li>
        <li><i class="fa fa-pencil-square"></i> <code>fa fa-pencil-square</code></li>
        <li><i class="fa fa-ellipsis-h"></i> <code>fa fa-ellipsis-h</code></li>
        <li><i class="fa fa-ellipsis-v"></i> <code>fa fa-ellipsis-v</code></li>
        <li><i class="fa fa-envelope"></i> <code>fa fa-envelope</code></li>
        <li><i class="fa fa-envelope-square"></i> <code>fa fa-envelope-square</code></li>
        <li><i class="fa fa-envelope-o"></i> <code>fa fa-envelope-o</code></li>
        <li><i class="fa fa-fax"></i> <code>fa fa-fax</code></li>
        <li><i class="fa fa-file-archive-o"></i> <code>fa fa-file-archive-o</code></li>
        <li><i class="fa fa-file-audio-o"></i> <code>fa fa-file-audio-o</code></li>
        <li><i class="fa fa-file-code-o"></i> <code>fa fa-file-code-o</code></li>
        <li><i class="fa fa-file-excel-o"></i> <code>fa fa-file-excel-o</code></li>
        <li><i class="fa fa-file-image-o"></i> <code>fa fa-file-image-o</code></li>
        <li><i class="fa fa-file-movie-o"></i> <code>fa fa-file-movie-o</code></li>
        <li><i class="fa fa-file-pdf-o"></i> <code>fa fa-file-pdf-o</code></li>
        <li><i class="fa fa-file-photo-o"></i> <code>fa fa-file-photo-o</code></li>
        <li><i class="fa fa-file-picture-o"></i> <code>fa fa-file-picture-o</code></li>
        <li><i class="fa fa-file-powerpoint-o"></i> <code>fa fa-file-powerpoint-o</code></li>
        <li><i class="fa fa-file-sound-o"></i> <code>fa fa-file-sound-o</code></li>
        <li><i class="fa fa-file-video-o"></i> <code>fa fa-file-video-o</code></li>
        <li><i class="fa fa-file-word-o"></i> <code>fa fa-file-word-o</code></li>
        <li><i class="fa fa-file-zip-o"></i> <code>fa fa-file-zip-o</code></li>
        <li><i class="fa fa-eraser"></i> <code>fa fa-eraser</code></li>
        <li><i class="fa fa-exchange"></i> <code>fa fa-exchange</code></li>
        <li><i class="fa fa-exclamation"></i> <code>fa fa-exclamation</code></li>
        <li><i class="fa fa-exclamation-circle"></i> <code>fa fa-exclamation-circle</code></li>
        <li><i class="fa fa-caret-square-o-right"></i> <code>fa fa-caret-square-o-right</code></li>
        <li><i class="fa fa-external-link"></i> <code>fa fa-external-link</code></li>
        <li><i class="fa fa-external-link-square"></i> <code>fa fa-external-link-square</code></li>
        <li><i class="fa fa-eye-slash"></i> <code>fa fa-eye-slash</code></li>
        <li><i class="fa fa-eye"></i> <code>fa fa-eye</code></li>
        <li><i class="fa fa-video-camera"></i> <code>fa fa-video-camera</code></li>
        <li><i class="fa fa-female"></i> <code>fa fa-female</code></li>
        <li><i class="fa fa-fighter-jet"></i> <code>fa fa-fighter-jet</code></li>
        <li><i class="fa fa-film"></i> <code>fa fa-film</code></li>
        <li><i class="fa fa-filter"></i> <code>fa fa-filter</code></li>
        <li><i class="fa fa-fire"></i> <code>fa fa-fire</code></li>
        <li><i class="fa fa-fire-extinguisher"></i> <code>fa fa-fire-extinguisher</code></li>
        <li><i class="fa fa-flag"></i> <code>fa fa-flag</code></li>
        <li><i class="fa fa-flag-o"></i> <code>fa fa-flag-o</code></li>
        <li><i class="fa fa-flag-checkered"></i> <code>fa fa-flag-checkered</code></li>
        <li><i class="fa fa-folder"></i> <code>fa fa-folder</code></li>
        <li><i class="fa fa-folder-o"></i> <code>fa fa-folder-o</code></li>
        <li><i class="fa fa-folder-open"></i> <code>fa fa-folder-open</code></li>
        <li><i class="fa fa-folder-open-o"></i> <code>fa fa-folder-open-o</code></li>
        <li><i class="fa fa-cutlery"></i> <code>fa fa-cutlery</code></li>
        <li><i class="fa fa-frown-o"></i> <code>fa fa-frown-o</code></li>
        <li><i class="fa fa-gamepad"></i> <code>fa fa-gamepad</code></li>
        <li><i class="fa fa-gear"></i> <code>fa fa-gear (alias)</code></li>
        <li><i class="fa fa-gears"></i> <code>fa fa-gears (alias)</code></li>
        <li><i class="fa fa-gift"></i> <code>fa fa-gift</code></li>
        <li><i class="fa fa-glass"></i> <code>fa fa-glass</code></li>
        <li><i class="fa fa-globe"></i> <code>fa fa-globe</code></li>
        <li><i class="fa fa-graduation-cap"></i> <code>fa fa-graduation-cap</code></li>
        <li><i class="fa fa-users"></i> <code>fa fa-users</code></li>
        <li><i class="fa fa-hdd-o"></i> <code>fa fa-hdd-o</code></li>
        <li><i class="fa fa-header"></i> <code>fa fa-header</code></li>
        <li><i class="fa fa-headphones"></i> <code>fa fa-headphones</code></li>
        <li><i class="fa fa-heart"></i> <code>fa fa-heart</code></li>
        <li><i class="fa fa-heart-o"></i> <code>fa fa-heart-o</code></li>
        <li><i class="fa fa-history"></i> <code>fa fa-history</code></li>
        <li><i class="fa fa-home"></i> <code>fa fa-home</code></li>
        <li><i class="fa fa-institution"></i> <code>fa fa-institution</code></li>
        <li><i class="fa fa-inbox"></i> <code>fa fa-inbox</code></li>
        <li><i class="fa fa-info"></i> <code>fa fa-info</code></li>
        <li><i class="fa fa-info-circle"></i> <code>fa fa-info-circle</code></li>
        <li><i class="fa fa-key"></i> <code>fa fa-key</code></li>
        <li><i class="fa fa-keyboard-o"></i> <code>fa fa-keyboard-o</code></li>
        <li><i class="fa fa-laptop"></i> <code>fa fa-laptop</code></li>
        <li><i class="fa fa-language"></i> <code>fa fa-language</code></li>
        <li><i class="fa fa-life-bouy"></i> <code>fa fa-life-bouy</code></li>
        <li><i class="fa fa-life-ring"></i> <code>fa fa-life-ring</code></li>
        <li><i class="fa fa-life-saver"></i> <code>fa fa-life-saver</code></li>
        <li><i class="fa fa-mortar-board"></i> <code>fa fa-mortar-board</code></li>
        <li><i class="fa fa-leaf"></i> <code>fa fa-leaf</code></li>
        <li><i class="fa fa-gavel"></i> <code>fa fa-gavel</code></li>
        <li><i class="fa fa-lemon-o"></i> <code>fa fa-lemon-o</code></li>
        <li><i class="fa fa-level-down"></i> <code>fa fa-level-down</code></li>
        <li><i class="fa fa-level-up"></i> <code>fa fa-level-up</code></li>
        <li><i class="fa fa-lightbulb-o"></i> <code>fa fa-lightbulb-o</code></li>
        <li><i class="fa fa-location-arrow"></i> <code>fa fa-location-arrow</code></li>
        <li><i class="fa fa-lock"></i> <code>fa fa-lock</code></li>
        <li><i class="fa fa-magic"></i> <code>fa fa-magic</code></li>
        <li><i class="fa fa-magnet"></i> <code>fa fa-magnet</code></li>
        <li><i class="fa fa-mail-reply"></i> <code>fa fa-mail-reply (alias)</code></li>
        <li><i class="fa fa-mail-reply-all"></i> <code>fa fa-mail-reply-all</code></li>
        <li><i class="fa fa-map-marker"></i> <code>fa fa-map-marker</code></li>
        <li><i class="fa fa-meh-o"></i> <code>fa fa-meh-o</code></li>
        <li><i class="fa fa-microphone"></i> <code>fa fa-microphone</code></li>
        <li><i class="fa fa-microphone-slash"></i> <code>fa fa-microphone-slash</code></li>
        <li><i class="fa fa-minus"></i> <code>fa fa-minus</code></li>
        <li><i class="fa fa-minus-circle"></i> <code>fa fa-minus-circle</code></li>
        <li><i class="fa fa-minus-square"></i> <code>fa fa-minus-square</code></li>
        <li><i class="fa fa-mobile"></i> <code>fa fa-mobile</code></li>
        <li><i class="fa fa-money"></i> <code>fa fa-money</code></li>
        <li><i class="fa fa-moon-o"></i> <code>fa fa-moon-o</code></li>
        <li><i class="fa fa-arrows"></i> <code>fa fa-arrows</code></li>
        <li><i class="fa fa-music"></i> <code>fa fa-music</code></li>
        <li><i class="fa fa-check"></i> <code>fa fa-check</code></li>
        <li><i class="fa fa-check-circle-o"></i> <code>fa fa-check-circle-o</code></li>
        <li><i class="fa fa-check-circle"></i> <code>fa fa-check-circle</code></li>
        <li><i class="fa fa-paper-plane"></i> <code>fa fa-paper-plane</code></li>
        <li><i class="fa fa-paper-plane-o"></i> <code>fa fa-paper-plane-o</code></li>
        <li><i class="fa fa-paragraph"></i> <code>fa fa-paragraph</code></li>
        <li><i class="fa fa-paw"></i> <code>fa fa-paw</code></li>
        <li><i class="fa fa-pencil"></i> <code>fa fa-pencil</code></li>
        <li><i class="fa fa-phone"></i> <code>fa fa-phone</code></li>
        <li><i class="fa fa-phone-square"></i> <code>fa fa-phone-square</code></li>
        <li><i class="fa fa-picture-o"></i> <code>fa fa-picture-o</code></li>
        <li><i class="fa fa-plane"></i> <code>fa fa-plane</code></li>
        <li><i class="fa fa-plus"></i> <code>fa fa-plus</code></li>
        <li><i class="fa fa-plus-circle"></i> <code>fa fa-plus-circle</code></li>
        <li><i class="fa fa-plus-square"></i> <code>fa fa-plus-square</code></li>
        <li><i class="fa fa-plus-square-o"></i> <code>fa fa-plus-square-o</code></li>
        <li><i class="fa fa-power-off"></i> <code>fa fa-power-off</code></li>
        <li><i class="fa fa-print"></i> <code>fa fa-print</code></li>
        <li><i class="fa fa-thumb-tack"></i> <code>fa fa-thumb-tack</code></li>
        <li><i class="fa fa-puzzle-piece"></i> <code>fa fa-puzzle-piece</code></li>
        <li><i class="fa fa-qrcode"></i> <code>fa fa-qrcode</code></li>
        <li><i class="fa fa-question"></i> <code>fa fa-question</code></li>
        <li><i class="fa fa-question-circle"></i> <code>fa fa-question-circle</code></li>
        <li><i class="fa fa-quote-left"></i> <code>fa fa-quote-left</code></li>
        <li><i class="fa fa-quote-right"></i> <code>fa fa-quote-right</code></li>
        <li><i class="fa fa-random"></i> <code>fa fa-random</code></li>
        <li><i class="fa fa-refresh"></i> <code>fa fa-refresh</code></li>
        <li><i class="fa fa-recycle"></i> <code>fa fa-recycle</code></li>
        <li><i class="fa fa-times"></i> <code>fa fa-times</code></li>
        <li><i class="fa fa-times-circle-o"></i> <code>fa fa-times-circle-o</code></li>
        <li><i class="fa fa-times-circle"></i> <code>fa fa-times-circle</code></li>
        <li><i class="fa fa-bars"></i> <code>fa fa-bars</code></li>
        <li><i class="fa fa-reply"></i> <code>fa fa-reply</code></li>
        <li><i class="fa fa-reply-all"></i> <code>fa fa-reply-all</code></li>
        <li><i class="fa fa-arrows-h"></i> <code>fa fa-arrows-h</code></li>
        <li><i class="fa fa-arrows-v"></i> <code>fa fa-arrows-v</code></li>
        <li><i class="fa fa-retweet"></i> <code>fa fa-retweet</code></li>
        <li><i class="fa fa-road"></i> <code>fa fa-road</code></li>
        <li><i class="fa fa-rocket"></i> <code>fa fa-rocket</code></li>
        <li><i class="fa fa-rss"></i> <code>fa fa-rss</code></li>
        <li><i class="fa fa-rss-square"></i> <code>fa fa-rss-square</code></li>
        <li><i class="fa fa-crosshairs"></i> <code>fa fa-crosshairs</code></li>
        <li><i class="fa fa-cube"></i> <code>fa fa-cube</code></li>
        <li><i class="fa fa-cubes"></i> <code>fa fa-cubes</code></li>
        <li><i class="fa fa-search"></i> <code>fa fa-search</code></li>
        <li><i class="fa fa-send"></i> <code>fa fa-send</code></li>
        <li><i class="fa fa-send-o"></i> <code>fa fa-send-o</code></li>
        <li><i class="fa fa-share"></i> <code>fa fa-share</code></li>
        <li><i class="fa fa-share-alt"></i> <code>fa fa-share-alt</code></li>
        <li><i class="fa fa-share-alt-square"></i> <code>fa fa-share-alt-square</code></li>
        <li><i class="fa fa-share-square-o"></i> <code>fa fa-share-square-o</code></li>
        <li><i class="fa fa-share-square"></i> <code>fa fa-share-square</code></li>
        <li><i class="fa fa-shield"></i> <code>fa fa-shield</code></li>
        <li><i class="fa fa-shopping-cart"></i> <code>fa fa-shopping-cart</code></li>
        <li><i class="fa fa-square"></i> <code>fa fa-square</code></li>
        <li><i class="fa fa-signal"></i> <code>fa fa-signal</code></li>
        <li><i class="fa fa-sign-in"></i> <code>fa fa-sign-in</code></li>
        <li><i class="fa fa-sign-out"></i> <code>fa fa-sign-out</code></li>
        <li><i class="fa fa-sitemap"></i> <code>fa fa-sitemap</code></li>
        <li><i class="fa fa-smile-o"></i> <code>fa fa-smile-o</code></li>
        <li><i class="fa fa-sliders"></i> <code>fa fa-sliders</code></li>
        <li><i class="fa fa-sort"></i> <code>fa fa-sort</code></li>
        <li><i class="fa fa-sort-alpha-asc"></i> <code>fa fa-sort-alpha-asc</code></li>
        <li><i class="fa fa-sort-alpha-desc"></i> <code>fa fa-sort-alpha-desc</code></li>
        <li><i class="fa fa-sort-amount-asc"></i> <code>fa fa-sort-amount-asc</code></li>
        <li><i class="fa fa-sort-amount-desc"></i> <code>fa fa-sort-amount-desc</code></li>
        <li><i class="fa fa-sort-numeric-asc"></i> <code>fa fa-sort-numeric-asc</code></li>
        <li><i class="fa fa-sort-numeric-desc"></i> <code>fa fa-sort-numeric-desc</code></li>
        <li><i class="fa fa-sort-asc"></i> <code>fa fa-sort-asc</code></li>
        <li><i class="fa fa-sort-desc"></i> <code>fa fa-sort-desc</code></li>
        <li><i class="fa fa-space-shuttle"></i> <code>fa fa-space-shuttle</code></li>
        <li><i class="fa fa-spoon"></i> <code>fa fa-spoon</code></li>
        <li><i class="fa fa-spinner"></i> <code>fa fa-spinner</code></li>
        <li><i class="fa fa-star"></i> <code>fa fa-star</code></li>
        <li><i class="fa fa-star-o"></i> <code>fa fa-star-o</code></li>
        <li><i class="fa fa-star-half"></i> <code>fa fa-star-half</code></li>
        <li><i class="fa fa-star-half-o"></i> <code>fa fa-star-half-o</code></li>
        <li><i class="fa fa-star-half-full"></i> <code>fa fa-star-half-full</code></li>
        <li><i class="fa fa-subscript"></i> <code>fa fa-subscript</code></li>
        <li><i class="fa fa-suitcase"></i> <code>fa fa-suitcase</code></li>
        <li><i class="fa fa-sun-o"></i> <code>fa fa-sun-o</code></li>
        <li><i class="fa fa-superscript"></i> <code>fa fa-superscript</code></li>
        <li><i class="fa fa-support"></i> <code>fa fa-support</code></li>
        <li><i class="fa fa-tablet"></i> <code>fa fa-tablet</code></li>
        <li><i class="fa fa-tag"></i> <code>fa fa-tag</code></li>
        <li><i class="fa fa-tags"></i> <code>fa fa-tags</code></li>
        <li><i class="fa fa-tasks"></i> <code>fa fa-tasks</code></li>
        <li><i class="fa fa-taxi"></i> <code>fa fa-taxi</code></li>
        <li><i class="fa fa-terminal"></i> <code>fa fa-terminal</code></li>
        <li><i class="fa fa-tree"></i> <code>fa fa-tree</code></li>
        <li><i class="fa fa-thumbs-down"></i> <code>fa fa-thumbs-down</code></li>
        <li><i class="fa fa-thumbs-o-down"></i> <code>fa fa-thumbs-o-down</code></li>
        <li><i class="fa fa-thumbs-up"></i> <code>fa fa-thumbs-up</code></li>
        <li><i class="fa fa-thumbs-o-up"></i> <code>fa fa-thumbs-o-up</code></li>
        <li><i class="fa fa-ticket"></i> <code>fa fa-ticket</code></li>
        <li><i class="fa fa-clock-o"></i> <code>fa fa-time</code></li>
        <li><i class="fa fa-tint"></i> <code>fa fa-tint</code></li>
        <li><i class="fa fa-trash-o"></i> <code>fa fa-trash-o</code></li>
        <li><i class="fa fa-trophy"></i> <code>fa fa-trophy</code></li>
        <li><i class="fa fa-truck"></i> <code>fa fa-truck</code></li>
        <li><i class="fa fa-umbrella"></i> <code>fa fa-umbrella</code></li>
        <li><i class="fa fa-university"></i> <code>fa fa-university</code></li>
        <li><i class="fa fa-unlock"></i> <code>fa fa-unlock</code></li>
        <li><i class="fa fa-unlock-alt"></i> <code>fa fa-unlock-alt</code></li>
        <li><i class="fa fa-arrow-circle-o-up"></i> <code>fa fa-arrow-circle-o-up</code></li>
        <li><i class="fa fa-upload"></i> <code>fa fa-upload</code></li>
        <li><i class="fa fa-user"></i> <code>fa fa-user</code></li>
        <li><i class="fa fa-volume-down"></i> <code>fa fa-volume-down</code></li>
        <li><i class="fa fa-volume-off"></i> <code>fa fa-volume-off</code></li>
        <li><i class="fa fa-volume-up"></i> <code>fa fa-volume-up</code></li>
        <li><i class="fa fa-exclamation-triangle"></i> <code>fa fa-exclamation-triangle</code></li>
        <li><i class="fa fa-wrench"></i> <code>fa fa-wrench</code></li>
        <li><i class="fa fa-search-plus"></i> <code>fa fa-search-plus</code></li>
        <li><i class="fa fa-search-minus"></i> <code>fa fa-search-minus</code></li>
    </ul>
    <!-- END Web Application Icons -->

    <!-- Currency Icons -->
    <h4 class="sub-header">Currency Icons</h4>
    <ul class="iconset-list clearfix">
        <li><i class="fa fa-bitcoin"></i> <code>fa fa-bitcoin (alias)</code></li>
        <li><i class="fa fa-btc"></i> <code>fa fa-btc</code></li>
        <li><i class="fa fa-ra"></i> <code>fa fa-ra</code></li>
        <li><i class="fa fa-rebel"></i> <code>fa fa-rebel</code></li>
        <li><i class="fa fa-rub"></i> <code>fa fa-rub</code></li>
        <li><i class="fa fa-ruble"></i> <code>fa fa-ruble (alias)</code></li>
        <li><i class="fa fa-rouble"></i> <code>fa fa-rouble (alias)</code></li>
        <li><i class="fa fa-dollar"></i> <code>fa fa-dollar</code></li>
        <li><i class="fa fa-eur"></i> <code>fa fa-eur</code></li>
        <li><i class="fa fa-euro"></i> <code>fa fa-euro (alias)</code></li>
        <li><i class="fa fa-gbp"></i> <code>fa fa-gbp</code></li>
        <li><i class="fa fa-inr"></i> <code>fa fa-inr</code></li>
        <li><i class="fa fa-jpy"></i> <code>fa fa-jpy</code></li>
        <li><i class="fa fa-krw"></i> <code>fa fa-krw</code></li>
        <li><i class="fa fa-rupee"></i> <code>fa fa-rupee (alias)</code></li>
        <li><i class="fa fa-try"></i> <code>fa fa-try</code></li>
        <li><i class="fa fa-turkish-lira"></i> <code>fa fa-turkish-lira (alias)</code></li>
        <li><i class="fa fa-usd"></i> <code>fa fa-usd (alias)</code></li>
        <li><i class="fa fa-won"></i> <code>fa fa-won (alias)</code></li>
        <li><i class="fa fa-yen"></i> <code>fa fa-yen (alias)</code></li>
    </ul>
    <!-- END Currency Icons -->

    <!-- Text Editor Icons -->
    <h4 class="sub-header">Text Editor Icons</h4>
    <ul class="iconset-list clearfix">
        <li><i class="fa fa-align-center"></i> <code>fa fa-align-center</code></li>
        <li><i class="fa fa-align-justify"></i> <code>fa fa-align-justify</code></li>
        <li><i class="fa fa-align-left"></i> <code>fa fa-align-left</code></li>
        <li><i class="fa fa-align-right"></i> <code>fa fa-align-right</code></li>
        <li><i class="fa fa-bold"></i> <code>fa fa-bold</code></li>
        <li><i class="fa fa-columns"></i> <code>fa fa-columns</code></li>
        <li><i class="fa fa-files-o"></i> <code>fa fa-files-o</code></li>
        <li><i class="fa fa-scissors"></i> <code>fa fa-scissors</code></li>
        <li><i class="fa fa-eraser"></i> <code>fa fa-eraser</code></li>
        <li><i class="fa fa-file"></i> <code>fa fa-file</code></li>
        <li><i class="fa fa-file-o"></i> <code>fa fa-file-o</code></li>
        <li><i class="fa fa-file-text"></i> <code>fa fa-file-text</code></li>
        <li><i class="fa fa-file-text-o"></i> <code>fa fa-file-text-o</code></li>
        <li><i class="fa fa-font"></i> <code>fa fa-font</code></li>
        <li><i class="fa fa-outdent"></i> <code>fa fa-outdent</code></li>
        <li><i class="fa fa-indent"></i> <code>fa fa-indent</code></li>
        <li><i class="fa fa-italic"></i> <code>fa fa-italic</code></li>
        <li><i class="fa fa-link"></i> <code>fa fa-link</code></li>
        <li><i class="fa fa-list"></i> <code>fa fa-list</code></li>
        <li><i class="fa fa-list-alt"></i> <code>fa fa-list-alt</code></li>
        <li><i class="fa fa-list-ol"></i> <code>fa fa-list-ol</code></li>
        <li><i class="fa fa-list-ul"></i> <code>fa fa-list-ul</code></li>
        <li><i class="fa fa-paperclip"></i> <code>fa fa-paperclip</code></li>
        <li><i class="fa fa-paperclip"></i> <code>fa fa-paperclip (alias)</code></li>
        <li><i class="fa fa-clipboard"></i> <code>fa fa-clipboard</code></li>
        <li><i class="fa fa-repeat"></i> <code>fa fa-repeat</code></li>
        <li><i class="fa fa-rotate-left"></i> <code>fa fa-rotate-left (alias)</code></li>
        <li><i class="fa fa-rotate-right"></i> <code>fa fa-rotate-right (alias)</code></li>
        <li><i class="fa fa-floppy-o"></i> <code>fa fa-floppy-o</code></li>
        <li><i class="fa fa-strikethrough"></i> <code>fa fa-strikethrough</code></li>
        <li><i class="fa fa-table"></i> <code>fa fa-table</code></li>
        <li><i class="fa fa-text-height"></i> <code>fa fa-text-height</code></li>
        <li><i class="fa fa-text-width"></i> <code>fa fa-text-width</code></li>
        <li><i class="fa fa-th"></i> <code>fa fa-th</code></li>
        <li><i class="fa fa-th-large"></i> <code>fa fa-th-large</code></li>
        <li><i class="fa fa-th-list"></i> <code>fa fa-th-list</code></li>
        <li><i class="fa fa-underline"></i> <code>fa fa-underline</code></li>
        <li><i class="fa fa-undo"></i> <code>fa fa-undo</code></li>
        <li><i class="fa fa-chain-broken"></i> <code>fa fa-chain-broken</code></li>
    </ul>
    <!-- END Text Editor Icons -->

    <!-- Directional Icons -->
    <h4 class="sub-header">Directional Icons</h4>
    <ul class="iconset-list clearfix">
        <li><i class="fa fa-angle-down"></i> <code>fa fa-angle-down</code></li>
        <li><i class="fa fa-angle-left"></i> <code>fa fa-angle-left</code></li>
        <li><i class="fa fa-angle-right"></i> <code>fa fa-angle-right</code></li>
        <li><i class="fa fa-angle-up"></i> <code>fa fa-angle-up</code></li>
        <li><i class="fa fa-arrow-down"></i> <code>fa fa-arrow-down</code></li>
        <li><i class="fa fa-arrow-left"></i> <code>fa fa-arrow-left</code></li>
        <li><i class="fa fa-arrow-right"></i> <code>fa fa-arrow-right</code></li>
        <li><i class="fa fa-arrow-up"></i> <code>fa fa-arrow-up</code></li>
        <li><i class="fa fa-caret-down"></i> <code>fa fa-caret-down</code></li>
        <li><i class="fa fa-caret-left"></i> <code>fa fa-caret-left</code></li>
        <li><i class="fa fa-caret-right"></i> <code>fa fa-caret-right</code></li>
        <li><i class="fa fa-caret-up"></i> <code>fa fa-caret-up</code></li>
        <li><i class="fa fa-caret-square-o-down"></i> <code>fa fa-caret-square-o-down</code></li>
        <li><i class="fa fa-caret-square-o-left"></i> <code>fa fa-caret-square-o-left</code></li>
        <li><i class="fa fa-caret-square-o-right"></i> <code>fa fa-caret-square-o-right</code></li>
        <li><i class="fa fa-caret-square-o-up"></i> <code>fa fa-caret-square-o-up</code></li>
        <li><i class="fa fa-chevron-down"></i> <code>fa fa-chevron-down</code></li>
        <li><i class="fa fa-chevron-left"></i> <code>fa fa-chevron-left</code></li>
        <li><i class="fa fa-chevron-right"></i> <code>fa fa-chevron-right</code></li>
        <li><i class="fa fa-chevron-circle-down"></i> <code>fa fa-chevron-circle-down</code></li>
        <li><i class="fa fa-chevron-circle-left"></i> <code>fa fa-chevron-circle-left</code></li>
        <li><i class="fa fa-chevron-circle-right"></i> <code>fa fa-chevron-circle-right</code></li>
        <li><i class="fa fa-chevron-circle-up"></i> <code>fa fa-chevron-circle-up</code></li>
        <li><i class="fa fa-chevron-up"></i> <code>fa fa-chevron-up</code></li>
        <li><i class="fa fa-arrow-circle-down"></i> <code>fa fa-arrow-circle-down</code></li>
        <li><i class="fa fa-arrow-circle-left"></i> <code>fa fa-arrow-circle-left</code></li>
        <li><i class="fa fa-arrow-circle-right"></i> <code>fa fa-arrow-circle-right</code></li>
        <li><i class="fa fa-arrow-circle-up"></i> <code>fa fa-arrow-circle-up</code></li>
        <li><i class="fa fa-arrow-circle-o-down"></i> <code>fa fa-arrow-circle-o-down</code></li>
        <li><i class="fa fa-arrow-circle-o-left"></i> <code>fa fa-arrow-circle-o-left</code></li>
        <li><i class="fa fa-arrow-circle-o-right"></i> <code>fa fa-arrow-circle-o-right</code></li>
        <li><i class="fa fa-arrow-circle-o-up"></i> <code>fa fa-arrow-circle-o-up</code></li>
        <li><i class="fa fa-angle-double-down"></i> <code>fa fa-angle-double-down</code></li>
        <li><i class="fa fa-angle-double-left"></i> <code>fa fa-angle-double-left</code></li>
        <li><i class="fa fa-angle-double-right"></i> <code>fa fa-angle-double-right</code></li>
        <li><i class="fa fa-angle-double-up"></i> <code>fa fa-angle-double-up</code></li>
        <li><i class="fa fa-hand-o-down"></i> <code>fa fa-hand-o-down</code></li>
        <li><i class="fa fa-hand-o-left"></i> <code>fa fa-hand-o-left</code></li>
        <li><i class="fa fa-hand-o-right"></i> <code>fa fa-hand-o-right</code></li>
        <li><i class="fa fa-hand-o-up"></i> <code>fa fa-hand-o-up</code></li>
        <li><i class="fa fa-long-arrow-down"></i> <code>fa fa-long-arrow-down</code></li>
        <li><i class="fa fa-long-arrow-left"></i> <code>fa fa-long-arrow-left</code></li>
        <li><i class="fa fa-long-arrow-right"></i> <code>fa fa-long-arrow-right</code></li>
        <li><i class="fa fa-long-arrow-up"></i> <code>fa fa-long-arrow-up</code></li>
    </ul>
    <!-- END Directional Icons -->

    <!-- Video Player Icons -->
    <h4 class="sub-header">Video Player Icons</h4>
    <ul class="iconset-list clearfix">
        <li><i class="fa fa-backward"></i> <code>fa fa-backward</code></li>
        <li><i class="fa fa-eject"></i> <code>fa fa-eject</code></li>
        <li><i class="fa fa-fast-backward"></i> <code>fa fa-fast-backward</code></li>
        <li><i class="fa fa-fast-forward"></i> <code>fa fa-fast-forward</code></li>
        <li><i class="fa fa-forward"></i> <code>fa fa-forward</code></li>
        <li><i class="fa fa-arrows-alt"></i> <code>fa fa-arrows-alt</code></li>
        <li><i class="fa fa-pause"></i> <code>fa fa-pause</code></li>
        <li><i class="fa fa-play"></i> <code>fa fa-play</code></li>
        <li><i class="fa fa-play-circle-o"></i> <code>fa fa-play-circle-o</code></li>
        <li><i class="fa fa-play-circle"></i> <code>fa fa-play-circle</code></li>
        <li><i class="fa fa-expand"></i> <code>fa fa-expand</code></li>
        <li><i class="fa fa-compress"></i> <code>fa fa-compress</code></li>
        <li><i class="fa fa-step-backward"></i> <code>fa fa-step-backward</code></li>
        <li><i class="fa fa-step-forward"></i> <code>fa fa-step-forward</code></li>
        <li><i class="fa fa-stop"></i> <code>fa fa-stop</code></li>
        <li><i class="fa fa-youtube-play"></i> <code>fa fa-youtube-play</code></li>
    </ul>
    <!-- END Video Player Icons -->

    <!-- Brand Icons -->
    <h4 class="sub-header">Brand Icons</h4>
    <ul class="iconset-list clearfix">
        <li><i class="fa fa-adn"></i> <code>fa fa-adn</code></li>
        <li><i class="fa fa-android"></i> <code>fa fa-android</code></li>
        <li><i class="fa fa-apple"></i> <code>fa fa-apple</code></li>
        <li><i class="fa fa-behance"></i> <code>fa fa-behance</code></li>
        <li><i class="fa fa-behance-square"></i> <code>fa fa-behance-square</code></li>
        <li><i class="fa fa-bitbucket"></i> <code>fa fa-bitbucket</code></li>
        <li><i class="fa fa-bitbucket-square"></i> <code>fa fa-bitbucket-square</code></li>
        <li><i class="fa fa-bitcoin"></i> <code>fa fa-bitcoin (alias)</code></li>
        <li><i class="fa fa-btc"></i> <code>fa fa-btc</code></li>
        <li><i class="fa fa-css3"></i> <code>fa fa-css3</code></li>
        <li><i class="fa fa-codepen"></i> <code>fa fa-codepen</code></li>
        <li><i class="fa fa-delicious"></i> <code>fa fa-delicious</code></li>
        <li><i class="fa fa-deviantart"></i> <code>fa fa-codepen</code></li>
        <li><i class="fa fa-digg"></i> <code>fa fa-digg</code></li>
        <li><i class="fa fa-dribbble"></i> <code>fa fa-dribbble</code></li>
        <li><i class="fa fa-dropbox"></i> <code>fa fa-dropbox</code></li>
        <li><i class="fa fa-drupal"></i> <code>fa fa-drupal</code></li>
        <li><i class="fa fa-empire"></i> <code>fa fa-empire</code></li>
        <li><i class="fa fa-facebook"></i> <code>fa fa-facebook</code></li>
        <li><i class="fa fa-facebook-square"></i> <code>fa fa-facebook-square</code></li>
        <li><i class="fa fa-flickr"></i> <code>fa fa-flickr</code></li>
        <li><i class="fa fa-foursquare"></i> <code>fa fa-foursquare</code></li>
        <li><i class="fa fa-github"></i> <code>fa fa-github</code></li>
        <li><i class="fa fa-github-alt"></i> <code>fa fa-github-alt</code></li>
        <li><i class="fa fa-github-square"></i> <code>fa fa-github-square</code></li>
        <li><i class="fa fa-gittip"></i> <code>fa fa-gittip</code></li>
        <li><i class="fa fa-ge"></i> <code>fa fa-ge</code></li>
        <li><i class="fa fa-git"></i> <code>fa fa-git</code></li>
        <li><i class="fa fa-git-square"></i> <code>fa fa-git-square</code></li>
        <li><i class="fa fa-google"></i> <code>fa fa-google</code></li>
        <li><i class="fa fa-google-plus"></i> <code>fa fa-google-plus</code></li>
        <li><i class="fa fa-google-plus-square"></i> <code>fa fa-google-plus-square</code></li>
        <li><i class="fa fa-hacker-news"></i> <code>fa fa-hacker-news</code></li>
        <li><i class="fa fa-html5"></i> <code>fa fa-html5</code></li>
        <li><i class="fa fa-joomla"></i> <code>fa fa-joomla</code></li>
        <li><i class="fa fa-jsfiddle"></i> <code>fa fa-jsfiddle</code></li>
        <li><i class="fa fa-instagram"></i> <code>fa fa-instagram</code></li>
        <li><i class="fa fa-linkedin"></i> <code>fa fa-linkedin</code></li>
        <li><i class="fa fa-linkedin-square"></i> <code>fa fa-linkedin-square</code></li>
        <li><i class="fa fa-linux"></i> <code>fa fa-linux</code></li>
        <li><i class="fa fa-maxcdn"></i> <code>fa fa-maxcdn</code></li>
        <li><i class="fa fa-openid"></i> <code>fa fa-openid</code></li>
        <li><i class="fa fa-pagelines"></i> <code>fa fa-pagelines</code></li>
        <li><i class="fa fa-pied-piper"></i> <code>fa fa-pied-piper</code></li>
        <li><i class="fa fa-pied-piper-alt"></i> <code>fa fa-pied-piper-alt</code></li>
        <li><i class="fa fa-pinterest"></i> <code>fa fa-pinterest</code></li>
        <li><i class="fa fa-pinterest-square"></i> <code>fa fa-pinterest-square</code></li>
        <li><i class="fa fa-qq"></i> <code>fa fa-qq</code></li>
        <li><i class="fa fa-reddit"></i> <code>fa fa-reddit</code></li>
        <li><i class="fa fa-reddit-square"></i> <code>fa fa-reddit-square</code></li>
        <li><i class="fa fa-renren"></i> <code>fa fa-renren</code></li>
        <li><i class="fa fa-skype"></i> <code>fa fa-skype</code></li>
        <li><i class="fa fa-slack"></i> <code>fa fa-slack</code></li>
        <li><i class="fa fa-soundcloud"></i> <code>fa fa-soundcloud</code></li>
        <li><i class="fa fa-spotify"></i> <code>fa fa-spotify</code></li>
        <li><i class="fa fa-stack-overflow"></i> <code>fa fa-stack-overflow</code></li>
        <li><i class="fa fa-stack-exchange"></i> <code>fa fa-stack-exchange</code></li>
        <li><i class="fa fa-steam"></i> <code>fa fa-steam</code></li>
        <li><i class="fa fa-steam-square"></i> <code>fa fa-steam-square</code></li>
        <li><i class="fa fa-stumbleupon"></i> <code>fa fa-stumbleupon</code></li>
        <li><i class="fa fa-stumbleupon-circle"></i> <code>fa fa-stumbleupon-circle</code></li>
        <li><i class="fa fa-tencent-weibo"></i> <code>fa fa-tencent-weibo</code></li>
        <li><i class="fa fa-trello"></i> <code>fa fa-trello</code></li>
        <li><i class="fa fa-tumblr"></i> <code>fa fa-tumblr</code></li>
        <li><i class="fa fa-tumblr-square"></i> <code>fa fa-tumblr-square</code></li>
        <li><i class="fa fa-twitter"></i> <code>fa fa-twitter</code></li>
        <li><i class="fa fa-twitter-square"></i> <code>fa fa-twitter-square</code></li>
        <li><i class="fa fa-vimeo-square"></i> <code>fa fa-vimeo-square</code></li>
        <li><i class="fa fa-vine"></i> <code>fa fa-vine</code></li>
        <li><i class="fa fa-vk"></i> <code>fa fa-vk</code></li>
        <li><i class="fa fa-wechat"></i> <code>fa fa-wechat</code></li>
        <li><i class="fa fa-weibo"></i> <code>fa fa-weibo</code></li>
        <li><i class="fa fa-weixin"></i> <code>fa fa-weixin</code></li>
        <li><i class="fa fa-windows"></i> <code>fa fa-windows</code></li>
        <li><i class="fa fa-wordpress"></i> <code>fa fa-wordpress</code></li>
        <li><i class="fa fa-xing"></i> <code>fa fa-xing</code></li>
        <li><i class="fa fa-xing-square"></i> <code>fa fa-xing-square</code></li>
        <li><i class="fa fa-yahoo"></i> <code>fa fa-yahoo</code></li>
        <li><i class="fa fa-youtube"></i> <code>fa fa-youtube</code></li>
        <li><i class="fa fa-youtube-play"></i> <code>fa fa-youtube-play</code></li>
        <li><i class="fa fa-youtube-square"></i> <code>fa fa-youtube-square</code></li>
    </ul>
    <!-- END Brand Icons -->

    <!-- Medical Icons -->
    <h4 class="sub-header">Medical Icons</h4>
    <ul class="iconset-list clearfix">
        <li><i class="fa fa-ambulance"></i> <code>fa fa-ambulance</code></li>
        <li><i class="fa fa-h-square"></i> <code>fa fa-h-square</code></li>
        <li><i class="fa fa-hospital-o"></i> <code>fa fa-hospital-o</code></li>
        <li><i class="fa fa-medkit"></i> <code>fa fa-medkit</code></li>
        <li><i class="fa fa-plus-square"></i> <code>fa fa-plus-square</code></li>
        <li><i class="fa fa-stethoscope"></i> <code>fa fa-stethoscope</code></li>
        <li><i class="fa fa-user-md"></i> <code>fa fa-user-md</code></li>
        <li><i class="fa fa-wheelchair"></i> <code>fa fa-wheelchair</code></li>
    </ul>
    <!-- END Medical Icons -->
</div>
<!-- END Page Content -->

<?php include 'inc/footer.php'; // Footer and scripts ?>
<?php include 'inc/bottom.php'; // Close body and html tags ?>